ENV:
  CLIENT_ID: eminem
  CLIENT_SECRET: 0922
  REDIRECT_URL: http://localhost:4000/callback
  AUTH_SERVER_AUTHORIZE_ENDPOINT: http://localhost:3000/authorize
  AUTH_SERVER_TOKEN_ENDPOINT: http://localhost:3000/token
